export default (Prefix: string) => [
	`${Prefix}/platform/telemetry/`,
	`${Prefix}/workbench/contrib/bracketPairColorizer2Telemetry/`,
	`${Prefix}/workbench/contrib/telemetry/`,
	`${Prefix}/workbench/services/telemetry/`,

	`${Prefix}/platform/telemetry/browser/errorTelemetry.js`,
	`${Prefix}/platform/telemetry/common/errorTelemetry.js`,
	`${Prefix}/platform/telemetry/common/remoteTelemetryChannel.js`,
	`${Prefix}/platform/telemetry/common/serverTelemetryService.js`,
	`${Prefix}/platform/telemetry/common/telemetry.js`,
	`${Prefix}/platform/telemetry/common/telemetryIpc.js`,
	`${Prefix}/platform/telemetry/common/telemetryLogAppender.js`,
	`${Prefix}/platform/telemetry/common/telemetryService.js`,
	`${Prefix}/platform/telemetry/common/telemetryUtils.js`,
	`${Prefix}/workbench/api/browser/mainThreadTelemetry.js`,
	`${Prefix}/workbench/api/common/extHostTelemetry.js`,
	`${Prefix}/workbench/contrib/bracketPairColorizer2Telemetry/browser/bracketPairColorizer2Telemetry.contribution.js`,
	`${Prefix}/workbench/contrib/chat/common/chatServiceTelemetry.js`,
	`${Prefix}/workbench/contrib/debug/common/debugTelemetry.js`,
	`${Prefix}/workbench/contrib/mergeEditor/browser/telemetry.js`,
	`${Prefix}/workbench/contrib/telemetry/browser/telemetry.contribution.js`,
	`${Prefix}/workbench/contrib/terminal/browser/terminalTelemetry.js`,
	`${Prefix}/workbench/contrib/terminalContrib/suggest/browser/terminalSuggestTelemetry.js`,
	`${Prefix}/workbench/services/telemetry/browser/telemetryService.js`,
];
