declare namespace FileSystemPolyfill_default {
    export { installFileSystemPolyfill as install };
    export { fs as module };
    export { readFile };
    export { writeFile };
    export { unlink };
    export { rm };
    export { rename };
    export { copyFile };
    export { mkdir };
    export { rmdir };
    export { readdir };
    export { stat };
    export { exists };
}
export function installFileSystemPolyfill(): void;
declare namespace fs {
    export { readFile };
    export { writeFile };
    export { unlink };
    export { rm };
    export { rename };
    export { copyFile };
    export { mkdir };
    export { rmdir };
    export { readdir };
    export { stat };
    export { exists };
    export namespace constants {
        let O_RDONLY: number;
        let O_WRONLY: number;
        let O_RDWR: number;
        let O_CREAT: number;
        let O_TRUNC: number;
        let O_APPEND: number;
    }
    export { open };
    export { read };
    export { write };
    export { close };
    export { readFileSync };
    export { writeFileSync };
    export { watch };
    export { watchFile };
    export { symlink };
    export { readlink };
    export { chmod };
    export { chown };
    export namespace promises {
        export { readFile };
        export { writeFile };
        export { unlink };
        export { rm };
        export { rename };
        export { copyFile };
        export { mkdir };
        export { rmdir };
        export { readdir };
        export { stat };
        export { exists };
    }
}
declare function readFile(path: any, options: any): Promise<any>;
declare function writeFile(path: any, data: any, options: any): Promise<void>;
declare function unlink(path: any): Promise<void>;
declare function rm(path: any, options: any): Promise<void>;
declare function rename(oldPath: any, newPath: any): Promise<void>;
declare function copyFile(src: any, dest: any, options: any): Promise<void>;
declare function mkdir(path: any, options: any): Promise<void>;
declare function rmdir(path: any): Promise<void>;
declare function readdir(path: any, options: any): Promise<any>;
declare function stat(path: any): Promise<{
    dev: number;
    ino: number;
    mode: number;
    nlink: number;
    uid: number;
    gid: number;
    rdev: number;
    size: any;
    atimeMs: number;
    mtimeMs: number;
    ctimeMs: number;
    birthtimeMs: number;
    atime: Date;
    mtime: Date;
    ctime: Date;
    birthtime: Date;
    isFile(): any;
    isDirectory(): any;
    isBlockDevice(): boolean;
    isCharacterDevice(): boolean;
    isSymbolicLink(): boolean;
    isFIFO(): boolean;
    isSocket(): boolean;
}>;
declare function exists(path: any): Promise<boolean>;
declare function open(): void;
declare function read(): void;
declare function write(): void;
declare function close(): void;
declare function readFileSync(): void;
declare function writeFileSync(): void;
declare function watch(): void;
declare function watchFile(): void;
declare function symlink(): void;
declare function readlink(): void;
declare function chmod(): void;
declare function chown(): void;
export { FileSystemPolyfill_default as default };
//# sourceMappingURL=FileSystemPolyfill.d.ts.map